services:
  - type: web
    name: mental-health-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MODEL_NAME
        value: meta-llama/Llama-3.2-3B-Instruct
      - key: PEFT_MODEL_PATH
        value: llama_fine_tuned
      - key: GUIDELINES_PATH
        value: guidelines.txt 